name: Build the js code
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install Depe...
        run: npm Install
      - name: Build
        run: npm run build