name: Build JS Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    Outputs:
      script-file: ${{ steps.publish.outputs.any-output-filename }}
    steps:
      # ✅ Checkout first
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Then setup Node.js so caching works
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # cache-dependency-path: Blog_Project/package-lock.json
          # Use in case you want to go inside  a folder and than use npm there 

      - name: Install dependencies
        # working-directory: Blog_Project
        run: npm ci

      - name: Build project
        # working-directory: Blog_Project
        run: npm run build
      
      - name: Publish js  filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'any-output-filename={}' >> $GITHUB_OUTPUT ';'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blog-project
          path: dist
          # path: |
          #   dist
          #   package.json
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: blog-project
      - name: Output
        run: ls 
      - name: Deploy...
        run: echo "Deploying....." 
