name: First-workflow
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print the name
        run: echo  "Hello world!"
      - name: Print the value
        run: echo  "Hello 123"
